repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.261
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      entry: __pypackages__/3.11/bin/ruff

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
